"""Domain models for phase-5 sentiment analysis.

This module contains Pydantic models for:
- SentimentPlan: Adaptive configuration generated by the planner sub-agent
- SentimentRecoveryPlan: LLM fallback response for failed analyses
- SentimentRuntimeConfig: Runtime controls for the sentiment agent
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field


@dataclass(slots=True)
class SentimentRuntimeConfig:
    """Runtime controls for sentiment analysis."""

    provider: str = "huggingface"
    model: str = "cardiffnlp/twitter-roberta-base-sentiment-latest"
    device: str | None = None
    batch_size: int = 16
    max_concurrency: int = 4
    max_documents_per_run: int = 500
    max_text_chars: int = 4000
    # Threshold for positive/negative/neutral classification
    positive_threshold: float = 0.6
    negative_threshold: float = 0.4
    # For topic-aware analysis
    include_topic_context: bool = True
    topic_context_weight: float = 0.3
    custom_keywords_positive: tuple[str, ...] = ()
    custom_keywords_negative: tuple[str, ...] = ()
    # Planner + LLM fallback settings
    llm_plan_enabled: bool = True
    llm_plan_sample_size: int = 10
    # LLM fallback settings
    llm_fallback_enabled: bool = True
    llm_fallback_sample_size: int = 10
    llm_fallback_max_chars: int = 2000
    # Confidence thresholds
    min_confidence_threshold: float = 0.5
    auto_retry_low_confidence: bool = True


class SentimentPlan(BaseModel):
    """Structured plan generated by SentimentPlannerAgent for adaptive behavior.

    This plan allows the sentiment agent to adapt its configuration based on
    the topic and sample documents being analyzed.
    """

    strategy_summary: str = Field(
        description="Brief reasoning for chosen sentiment strategy"
    )
    model: str | None = Field(
        default=None,
        description="Sentiment model to use (overrides default)",
    )
    positive_threshold: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Threshold above which text is considered positive",
    )
    negative_threshold: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Threshold below which text is considered negative",
    )
    include_topic_context: bool | None = Field(
        default=None,
        description="Whether to include topic context in analysis",
    )
    topic_context_weight: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Weight given to topic context in analysis",
    )
    min_confidence_threshold: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Minimum confidence required to accept result without retry",
    )
    auto_retry_low_confidence: bool | None = Field(
        default=None,
        description="Whether to automatically retry low-confidence analyses",
    )
    custom_keywords_positive: list[str] = Field(
        default_factory=list,
        description="Additional keywords that indicate positive sentiment",
    )
    custom_keywords_negative: list[str] = Field(
        default_factory=list,
        description="Additional keywords that indicate negative sentiment",
    )
    language_override: str | None = Field(
        default=None,
        description="Force specific language model (e.g., 'multilingual')",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in plan quality",
    )


class SentimentRecoveryPlan(BaseModel):
    """Structured response used by SentimentRecoveryAgent for failed cases.

    When the primary sentiment analysis fails or returns low confidence,
    this plan provides a fallback result.
    """

    status: Literal["accepted", "rejected", "needs_review"] = Field(
        description="Final decision for the sentiment analysis"
    )
    score: float = Field(
        ge=0.0,
        le=1.0,
        description="Sentiment score (0=negative, 0.5=neutral, 1=positive)",
    )
    label: str = Field(description="Sentiment label: positive, negative, or neutral")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in the sentiment prediction",
    )
    reason: str = Field(description="Short explanation of the decision")
    alternative_models_tried: list[str] = Field(
        default_factory=list,
        description="List of alternative models attempted",
    )
    recommended_plan_adjustments: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional runtime-config changes for future analyses",
    )
