"""Domain models for phase-4 adaptive cleaning."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field


@dataclass(slots=True)
class CleaningRuntimeConfig:
    """Runtime controls for deterministic/adaptive cleaning and QA sampling."""

    max_concurrency: int = 8
    max_documents_per_run: int = 500
    sample_review_rate: float = 0.05
    max_sample_reviews: int = 20
    min_clean_chars: int = 30
    max_clean_chars: int = 12000
    remove_punctuation: bool = True
    lowercase_text: bool = True
    replace_urls_with_token: bool = True
    replace_mentions_with_token: bool = True
    preserve_case_for_shouting: bool = False
    extraction_backends: tuple[str, ...] = (
        "content_fields",
        "trafilatura",
        "readability",
        "bs4",
    )
    min_alpha_ratio: float = 0.35
    max_url_ratio: float = 0.3
    max_symbol_ratio: float = 0.35
    reject_non_preferred_languages: bool = False
    preferred_languages: tuple[str, ...] = ("en",)
    enable_fuzzy_dedupe: bool = True
    fuzzy_dedupe_threshold: float = 93.0
    fuzzy_candidate_limit: int = 250
    llm_plan_enabled: bool = True
    llm_plan_sample_size: int = 24
    llm_plan_max_chars_per_sample: int = 1600
    llm_fallback_max_chars: int = 2200
    llm_force_full_rewrite: bool = False
    llm_fallback_enabled: bool = True
    custom_noise_patterns: tuple[str, ...] = (
        r"cookie(s)?\s+policy",
        r"accept\s+all\s+cookies",
        r"sign\s+in\s+to\s+continue",
        r"subscribe\s+for\s+more",
        r"javascript\s+is\s+disabled",
    )


@dataclass(slots=True)
class CleanerResult:
    """Normalized output from deterministic cleaner."""

    status: Literal["accepted", "duplicate", "too_short", "failed"]
    cleaned_text: str
    sentiment_text: str
    cleaned_hash: str | None
    source_text: str
    reason: str = ""
    quality_flags: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    features: dict[str, Any] = field(default_factory=dict)


class CleanerPlan(BaseModel):
    """Structured plan generated by CleanerPlannerAgent for adaptive behavior."""

    strategy_summary: str = Field(
        description="Brief reasoning for chosen cleaning strategy"
    )
    remove_punctuation: bool | None = None
    lowercase_text: bool | None = None
    replace_urls_with_token: bool | None = None
    replace_mentions_with_token: bool | None = None
    min_clean_chars: int | None = None
    max_clean_chars: int | None = None
    min_alpha_ratio: float | None = None
    max_url_ratio: float | None = None
    max_symbol_ratio: float | None = None
    preferred_languages: list[str] = Field(default_factory=list)
    reject_non_preferred_languages: bool | None = None
    enable_fuzzy_dedupe: bool | None = None
    fuzzy_dedupe_threshold: float | None = None
    custom_noise_patterns: list[str] = Field(default_factory=list)
    extra_remove_regexes: list[str] = Field(default_factory=list)
    replacement_rules: dict[str, str] = Field(default_factory=dict)
    confidence: float = Field(ge=0, le=1, description="Confidence in plan quality")


class CleanerRecoveryPlan(BaseModel):
    """Structured response used by LLM fallback / QA review."""

    status: Literal["accepted", "rejected", "manual_review"] = Field(
        description="Final quality decision for the cleaned text"
    )
    cleaned_text: str = Field(
        default="",
        description="Improved cleaned text when available",
    )
    reason: str = Field(description="Short explanation of the decision")
    quality_score: float = Field(
        ge=0,
        le=1,
        description="Confidence score for quality of cleaned text",
    )
    recommended_plan_adjustments: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional runtime-config deltas for future records.",
    )
